export { default as Navbar }           from './Navbar/Navbar.jsx'
export { default as Hero }             from './Hero/Hero.jsx'
export { default as Marquee }          from './Marquee/Marquee.jsx'
export { default as About }            from './About/About.jsx'
export { default as ExperienceSection} from './ExperienceSection/ExperienceSection.jsx'
export { default as Work }             from './Work/Work.jsx'
export { default as Contact }          from './Contact/Contact.jsx'
export { default as Footer }           from './Footer/Footer.jsx'
export { default as RecruiterView }    from './RecruiterView/RecruiterView.jsx'
